name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ashkeel/wails-build-action@a56973d
        with:
          build-name: strimertul
          build-platform: linux/amd64
          package: false
          go-version: 1.19