name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.18
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Wails
        if: inputs.build == 'true'
        run: go install github.com/wailsapp/wails/v2/cmd/wails@${{inputs.wails-version}}
        shell: bash
      - name: Install Linux Wails deps
        if: inputs.build == 'true' && runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu
        shell: bash
      - name: Install macOS Wails deps
        if: runner.os == 'macOS'
        run: brew install mitchellh/gon/gon
        shell: bash
      - name: Build App
        if: inputs.build == 'true' && runner.os == 'macOS'
        working-directory: ${{ inputs.app-working-directory }}
        run: wails build --platform ${{inputs.build-platform}} -webview2 ${{inputs.wails-build-webview2}} -o ${{inputs.build-name}}
        shell: bash
      - name: Build App
        if: inputs.build == 'true' &&  runner.os == 'Linux'
        working-directory: ${{ inputs.app-working-directory }}
        run: wails build --platform ${{inputs.build-platform}} -webview2 ${{inputs.wails-build-webview2}} -o ${{inputs.build-name}}
        shell: bash
      - name: Build App
        if: inputs.build == 'true' && runner.os == 'Windows'
        working-directory: ${{ inputs.app-working-directory }}
        run: wails build --platform ${{inputs.build-platform}} -webview2 ${{inputs.wails-build-webview2}} -o ${{inputs.build-name}}
        shell: bash