name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.18
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
      - name: Build app for all platforms
        run: |
          go install github.com/mitchellh/gox@latest
          gox -arch="amd64 arm" -os "windows linux" -ldflags "-X 'main.appVersion=`git describe --tags --always`'"
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            strimertul_*
